- name: Install dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - nginx
    - python3-venv
- name: "Create system user {{app_user}}"
  user:
    name: "{{app_user}}"
    group: "{{app_group}}"
    create_home: yes
    shell: /bin/false
    system: yes
    home: "{{base_dir}}"
  become: yes
- name: Clone the application
  git:
    repo: https://github.com/FOSDEM/volunteers.git
    dest: "{{base_dir}}/tool"
    version: master
  register: app_updated
  notify: Restart fosdem_volunteers
- name: Install dependencies inside a virtual environment
  pip:
    virtualenv: "{{base_dir}}/venv3"
    virtualenv_python: python3
    requirements: "{{base_dir}}/tool/requirements-frozen.txt"
  become: yes
  become_user: "{{app_user}}"
- name: Add gunicorn to venv
  pip:
    virtualenv: "{{base_dir}}/venv3"
    name: gunicorn
  become: yes
  become_user: "{{app_user}}"
- name: Create media directory
  file:
    path: "{{base_dir}}/tool/media/mugshots"
    state: directory
  become: yes
  become_user: "{{app_user}}"
- name: Check if localsettings exists
  stat:
    path: "{{ base_dir }}/tool/volunteer_mgmt"
  register: localsettings
- pause:
    prompt: "Please create localsettings.py in {{base_dir}}/tool/volunteer_mgmt"
  when: not localsettings.stat.exists
  notify: Restart fosdem_volunteers
- name: Run migrations/Collect static files
  django_manage:
    app_path: "{{base_dir}}/tool"
    command: "{{ item }}"
    virtualenv: "{{base_dir}}/venv3"
  become: yes
  become_user: "{{app_user}}"
  with_items:
    - migrate
    - collectstatic
  when: app_updated.changed
- name: install the tmpfiles.d conf
  become: true
  copy:
    content: d /run/volunteers 0755 {{ app_user }} {{ app_user }} - -
    dest: /usr/lib/tmpfiles.d/fosdem_volunteers.conf

- name: configure tmpfiles.d
  become: true
  command: systemd-tmpfiles --create

- name: Create systemd service file
  template:
    dest: /etc/systemd/system/fosdem_volunteers.service
    src: volunteers.service.j2
  become: yes
  notify: Restart fosdem_volunteers
- name: Install nginx configuration file
  template:
    dest: /etc/nginx/conf.d/fosdem_volunteers.conf
    src: nginx.conf.j2
  become: yes
  notify: Reload nginx
- name: Create cronjob to sync penta (hourly)
  become_user: "{{app_user}}"
  cron:
    name: Sync with penta
    job: "{{base_dir}}/venv3/bin/python {{base_dir}}/tool/manage.py sync_with_penta"
    minute: 0
    state: absent
  tags:
  - cron
- name: Sync volunteers for infodesk with penta
  become_user: "{{app_user}}"
  cron:
    name: Sync with penta
    job: "{{base_dir}}/venv3/bin/python {{base_dir}}/tool/manage.py sync_volunteers_with_penta_account"
    minute: 0
    state: absent
  tags:
  - cron
